// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pibbyyltgdtkzfjbqixw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpYmJ5eWx0Z2R0a3pmamJxaXh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3ODM1OTIsImV4cCI6MjA2NzM1OTU5Mn0.JhkU_yWcTOeoROlIwkiGpBjPQ46huaA4ktV2kb5mWqU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});