// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xbwisxnbtsodxtipdcrm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhid2lzeG5idHNvZHh0aXBkY3JtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MzY4NDcsImV4cCI6MjA2NzIxMjg0N30.6tULt7Ly5jyDL7xQPUnIEdy7ordurV4PvcJ9FJ9KY2I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});